# Generated by Django 4.2.11 on 2024-04-13 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='audio',
            field=models.FileField(upload_to='tours/audios/'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='photo',
            field=models.ImageField(upload_to='tours/photos/'),
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('location_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('location_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('audio', models.FileField(upload_to='stops/audios/')),
                ('image', models.ImageField(upload_to='stops/images/')),
                ('description', models.TextField(blank=True)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.tour')),
            ],
        ),
    ]
